"use client";
import Image from "next/image";
import { ArrowUpRight, Clock3, Lock } from "lucide-react";
import type { PartnerTask } from "@/types";

export function TaskCard({ task, onOpen }: { task: PartnerTask; onOpen: () => void }) {
  if (task.status === "locked") return <article className="task-card locked" aria-disabled="true"><div className="task-image"><Image src={task.image} alt={task.title} fill sizes="(max-width: 600px) 100vw, 420px" /></div><div className="task-body"><div className="task-meta"><span>{task.category}</span>{!task.lockReason && <span className="status-badge locked-badge"><Lock size={12} />Недоступно</span>}</div><div className="task-title-row"><h3>{task.title}</h3><strong>{task.payout_label}</strong></div><p>{task.description}</p><div className="task-footer"><span><Clock3 size={15} />{task.time_label}</span><span>Сложность · {task.difficulty}</span></div>{task.lockReason ? <div className="lock-reason" role="note"><Lock size={15} /><span>{task.lockReason}</span></div> : <button className="secondary-button" disabled>Недоступно</button>}</div></article>;
  return <article className="task-card"><div className="task-image"><Image src={task.image} alt={task.title} fill sizes="(max-width: 600px) 100vw, 420px" /></div><div className="task-body"><div className="task-meta"><span>{task.category}</span>{task.status === "started" && <span className="status-badge">Задание в процессе</span>}</div><div className="task-title-row"><h3>{task.title}</h3><strong>{task.payout_label}</strong></div><p>{task.description}</p><div className="task-footer"><span><Clock3 size={15} />{task.time_label}</span><span>Сложность · {task.difficulty}</span></div><button className="primary-button" onClick={onOpen}><span>{task.status === "started" ? "Продолжить" : "Выполнить"}</span><ArrowUpRight size={18} /></button></div></article>;
}
