"use client";
import Image from "next/image";
import { ArrowUpRight, ChevronDown, Clock3, X } from "lucide-react";
import { useState } from "react";
import { haptic, openExternal } from "@/components/telegram";
import type { PartnerTask } from "@/types";

export function TaskDetail({ task, initData, onClose, onStarted }: { task: PartnerTask; initData: string; onClose: () => void; onStarted: () => void }) {
  const [openEducation, setOpenEducation] = useState(false); const [error, setError] = useState("");
  const go = async () => { if (!task.url) return; try { const response = await fetch(`/api/tasks/${task.id}/start`, { method: "POST", headers: { "x-telegram-init-data": initData } }); if (!response.ok) throw new Error((await response.json()).error); haptic("impact"); onStarted(); openExternal(task.url); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось загрузить данные. Попробуйте ещё раз."); } };
  return <main className="detail-page"><button className="close-button" onClick={onClose} aria-label="Закрыть"><X size={20} /></button><div className="detail-image"><Image src={task.image} alt={task.title} fill sizes="100vw" priority /></div><section className="detail-card"><span className="eyebrow">{task.category}</span><div className="task-title-row"><h1>{task.title}</h1><strong>{task.payout_label}</strong></div><div className="detail-facts"><span><Clock3 size={16} />{task.time_label}</span><span>Сложность · {task.difficulty}</span></div><p>{task.description}</p><h2>Что предстоит сделать</h2><ol>{task.conditions?.map((item) => <li key={item}>{item}</li>)}</ol>{task.slug === "rko" && <><div className="note-block">{task.title && "Если у тебя уже есть ИП — не закрывай его самостоятельно. Сначала уточни ситуацию у менеджера. Если есть НПД, сообщи об этом менеджеру."}</div><button className="education-toggle" onClick={() => setOpenEducation(!openEducation)}>Что такое ИП на НПД?<ChevronDown className={openEducation ? "rotate" : ""} size={18} /></button>{openEducation && <p className="education-text">НПД — специальный налоговый режим для физических лиц и ИП при соблюдении установленных условий. Для НПД действуют специальные ставки налога в зависимости от типа дохода. При применении НПД отсутствует обязанность по уплате фиксированных страховых взносов за себя, однако режим имеет свои условия и ограничения. Перед оформлением уточни актуальные условия у менеджера и официальных источников.</p>}</>}{error && <p className="form-error">{error}</p>}<button className="primary-button" onClick={() => void go()} disabled={!task.url}><span>{task.url ? (task.slug === "rko" ? "Написать менеджеру" : task.slug === "tbank" ? "Оформить карту" : "Перейти к заданию") : "Скоро будет доступно"}</span>{task.url && <ArrowUpRight size={19} />}</button></section></main>;
}
